# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(499, 548)
        Form.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:rgb(1, 181, 180)")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(40, 210, 401, 331))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setStyleSheet("\n"
"background-color:rgb(39, 208, 202);")
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Login = QtWidgets.QWidget()
        self.Login.setObjectName("Login")
        self.login = QtWidgets.QLineEdit(self.Login)
        self.login.setGeometry(QtCore.QRect(80, 50, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.login.setFont(font)
        self.login.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.login.setMouseTracking(False)
        self.login.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:rgb(234, 249, 249)")
        self.login.setObjectName("login")
        self.label_icone = QtWidgets.QLabel(self.Login)
        self.label_icone.setGeometry(QtCore.QRect(30, 50, 51, 51))
        self.label_icone.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:rgb(14, 165, 160)")
        self.label_icone.setText("")
        self.label_icone.setPixmap(QtGui.QPixmap("icon/usuario_button.png"))
        self.label_icone.setAlignment(QtCore.Qt.AlignCenter)
        self.label_icone.setObjectName("label_icone")
        self.senha = QtWidgets.QLineEdit(self.Login)
        self.senha.setGeometry(QtCore.QRect(80, 130, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.senha.setFont(font)
        self.senha.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:rgb(234, 249, 249)")
        self.senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.senha.setObjectName("senha")
        self.label_icone1 = QtWidgets.QLabel(self.Login)
        self.label_icone1.setGeometry(QtCore.QRect(30, 130, 51, 51))
        self.label_icone1.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:rgb(14, 165, 160)")
        self.label_icone1.setText("")
        self.label_icone1.setPixmap(QtGui.QPixmap("icon/password.png"))
        self.label_icone1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_icone1.setObjectName("label_icone1")
        self.bt_connectar = QtWidgets.QPushButton(self.Login)
        self.bt_connectar.setGeometry(QtCore.QRect(70, 230, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.bt_connectar.setFont(font)
        self.bt_connectar.setStyleSheet("border-style:outset;\n"
"border-radius:8px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 170, 0);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icone py/sinal-de-visto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_connectar.setIcon(icon)
        self.bt_connectar.setObjectName("bt_connectar")
        self.bt_cancelar = QtWidgets.QPushButton(self.Login)
        self.bt_cancelar.setGeometry(QtCore.QRect(240, 230, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.bt_cancelar.setFont(font)
        self.bt_cancelar.setStyleSheet("border-style:outset;\n"
"border-radius:8px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 170, 0);")
        self.bt_cancelar.setIcon(icon)
        self.bt_cancelar.setObjectName("bt_cancelar")
        self.label_conexao = QtWidgets.QLabel(self.Login)
        self.label_conexao.setGeometry(QtCore.QRect(150, 190, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_conexao.setFont(font)
        self.label_conexao.setStyleSheet("color: black;\n"
"border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:rgb(39, 208, 202);")
        self.label_conexao.setText("")
        self.label_conexao.setObjectName("label_conexao")
        self.label_welcome = QtWidgets.QLabel(self.Login)
        self.label_welcome.setGeometry(QtCore.QRect(30, 20, 331, 23))
        self.label_welcome.setStyleSheet("font-family: Trebuchet MS;\n"
"font-size: 15px;\n"
"font-weight: bold;\n"
"color: white;\n"
"border:none;\n"
"text-decoration:underline;\n"
"color:white;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0,0,0), stop:1 rgba(1, 181, 180));\n"
"")
        self.label_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.label_welcome.setObjectName("label_welcome")
        self.progressBar = QtWidgets.QProgressBar(self.Login)
        self.progressBar.setGeometry(QtCore.QRect(0, 280, 411, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.tabWidget.addTab(self.Login, "")
        self.cadastro = QtWidgets.QWidget()
        self.cadastro.setObjectName("cadastro")
        self.Button_Cadastro = QtWidgets.QPushButton(self.cadastro)
        self.Button_Cadastro.setGeometry(QtCore.QRect(220, 260, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Button_Cadastro.setFont(font)
        self.Button_Cadastro.setStyleSheet("border-style:outset;\n"
"border-radius:8px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 170, 0);")
        self.Button_Cadastro.setObjectName("Button_Cadastro")
        self.nome_usuario = QtWidgets.QLineEdit(self.cadastro)
        self.nome_usuario.setGeometry(QtCore.QRect(80, 60, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nome_usuario.setFont(font)
        self.nome_usuario.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:rgb(234, 249, 249)")
        self.nome_usuario.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.nome_usuario.setText("")
        self.nome_usuario.setClearButtonEnabled(False)
        self.nome_usuario.setObjectName("nome_usuario")
        self.log_cadastro = QtWidgets.QLineEdit(self.cadastro)
        self.log_cadastro.setGeometry(QtCore.QRect(80, 110, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.log_cadastro.setFont(font)
        self.log_cadastro.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:rgb(234, 249, 249)")
        self.log_cadastro.setText("")
        self.log_cadastro.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.log_cadastro.setObjectName("log_cadastro")
        self.senha_cs1 = QtWidgets.QLineEdit(self.cadastro)
        self.senha_cs1.setGeometry(QtCore.QRect(80, 160, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.senha_cs1.setFont(font)
        self.senha_cs1.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:rgb(234, 249, 249)")
        self.senha_cs1.setText("")
        self.senha_cs1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.senha_cs1.setObjectName("senha_cs1")
        self.label_3 = QtWidgets.QLabel(self.cadastro)
        self.label_3.setGeometry(QtCore.QRect(50, 0, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setAcceptDrops(False)
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setStyleSheet("border-style:outset;\n"
"border-radius:8px;\n"
"border-width:0px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.senha_cs2 = QtWidgets.QLineEdit(self.cadastro)
        self.senha_cs2.setGeometry(QtCore.QRect(80, 210, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.senha_cs2.setFont(font)
        self.senha_cs2.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:rgb(234, 249, 249)")
        self.senha_cs2.setText("")
        self.senha_cs2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.senha_cs2.setObjectName("senha_cs2")
        self.icone = QtWidgets.QLabel(self.cadastro)
        self.icone.setGeometry(QtCore.QRect(30, 60, 51, 41))
        self.icone.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:rgb(14, 165, 160)")
        self.icone.setText("")
        self.icone.setPixmap(QtGui.QPixmap("icone py/user1.png"))
        self.icone.setObjectName("icone")
        self.icone_2 = QtWidgets.QLabel(self.cadastro)
        self.icone_2.setGeometry(QtCore.QRect(30, 110, 51, 41))
        self.icone_2.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:rgb(14, 165, 160)")
        self.icone_2.setText("")
        self.icone_2.setPixmap(QtGui.QPixmap("icone py/user1.png"))
        self.icone_2.setObjectName("icone_2")
        self.icone_3 = QtWidgets.QLabel(self.cadastro)
        self.icone_3.setGeometry(QtCore.QRect(30, 160, 51, 41))
        self.icone_3.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:rgb(14, 165, 160)")
        self.icone_3.setText("")
        self.icone_3.setPixmap(QtGui.QPixmap("icone py/user1.png"))
        self.icone_3.setObjectName("icone_3")
        self.icone_4 = QtWidgets.QLabel(self.cadastro)
        self.icone_4.setGeometry(QtCore.QRect(30, 210, 51, 41))
        self.icone_4.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:rgb(14, 165, 160)")
        self.icone_4.setText("")
        self.icone_4.setPixmap(QtGui.QPixmap("icone py/user1.png"))
        self.icone_4.setObjectName("icone_4")
        self.label_cadastro = QtWidgets.QLabel(self.cadastro)
        self.label_cadastro.setGeometry(QtCore.QRect(40, 260, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_cadastro.setFont(font)
        self.label_cadastro.setStyleSheet("color: white;\n"
"border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:rgb(39, 208, 202);")
        self.label_cadastro.setText("")
        self.label_cadastro.setObjectName("label_cadastro")
        self.tabWidget.addTab(self.cadastro, "")
        self.usuario = QtWidgets.QWidget()
        self.usuario.setObjectName("usuario")
        self.tableWidget = QtWidgets.QTableWidget(self.usuario)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 401, 251))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setAutoScroll(False)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setGridStyle(QtCore.Qt.DashDotLine)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Impact")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Impact")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Impact")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        self.chamar = QtWidgets.QPushButton(self.usuario)
        self.chamar.setGeometry(QtCore.QRect(10, 262, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        self.chamar.setFont(font)
        self.chamar.setStyleSheet("border-style:outset;\n"
"border-radius:8px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 170, 0);")
        self.chamar.setObjectName("chamar")
        self.limpar_grade = QtWidgets.QPushButton(self.usuario)
        self.limpar_grade.setGeometry(QtCore.QRect(320, 260, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        self.limpar_grade.setFont(font)
        self.limpar_grade.setStyleSheet("border-style:outset;\n"
"border-radius:8px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 170, 0);")
        self.limpar_grade.setObjectName("limpar_grade")
        self.deletar_us = QtWidgets.QPushButton(self.usuario)
        self.deletar_us.setGeometry(QtCore.QRect(170, 260, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        self.deletar_us.setFont(font)
        self.deletar_us.setStyleSheet("border-style:outset;\n"
"border-radius:8px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 170, 0);")
        self.deletar_us.setObjectName("deletar_us")
        self.tabWidget.addTab(self.usuario, "")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 231, 211))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icon/you.png"))
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(240, 90, 211, 71))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 10, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Full Pack 2025")
        font.setPointSize(22)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 255, 127);")
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setIndent(0)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.frame.raise_()
        self.label.raise_()
        self.tabWidget.raise_()
        self.label_2.setBuddy(self.usuario)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.limpar_grade.clicked.connect(self.tableWidget.clearSelection)
        self.limpar_grade.clicked.connect(self.tableWidget.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.bt_connectar.setText(_translate("Form", "CONECTAR"))
        self.bt_cancelar.setText(_translate("Form", "CANCELA"))
        self.label_welcome.setText(_translate("Form", "Bem vindo Usuario."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Login), _translate("Form", "LOGIN"))
        self.Button_Cadastro.setText(_translate("Form", "Salvar"))
        self.nome_usuario.setPlaceholderText(_translate("Form", "Digite seu nome "))
        self.log_cadastro.setPlaceholderText(_translate("Form", "Digite o login"))
        self.senha_cs1.setPlaceholderText(_translate("Form", "Digite a senha"))
        self.label_3.setText(_translate("Form", "Preencha Seus Dados"))
        self.senha_cs2.setPlaceholderText(_translate("Form", "Repita a senha"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cadastro), _translate("Form", "CADASTRO"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "NOME"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "LOGIN"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "SENHA"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.chamar.setText(_translate("Form", "Ver"))
        self.limpar_grade.setText(_translate("Form", "Limpar"))
        self.deletar_us.setText(_translate("Form", "Deletar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.usuario), _translate("Form", "USUARIO"))
        self.label_2.setText(_translate("Form", "Import"))
