# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'youyou.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1262, 788)
        MainWindow.setStyleSheet("color:white;\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 20, 1201, 701))
        self.stackedWidget.setStyleSheet("background: transparent;\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.TExt_Link = QtWidgets.QLabel(self.page1)
        self.TExt_Link.setGeometry(QtCore.QRect(300, 80, 421, 81))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(26)
        self.TExt_Link.setFont(font)
        self.TExt_Link.setStyleSheet("color:white;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0,0,0), stop:1 rgba(1, 181, 180));\n"
"")
        self.TExt_Link.setObjectName("TExt_Link")
        self.icone = QtWidgets.QLabel(self.page1)
        self.icone.setGeometry(QtCore.QRect(20, 50, 271, 221))
        self.icone.setStyleSheet("")
        self.icone.setText("")
        self.icone.setPixmap(QtGui.QPixmap("icon/you.png"))
        self.icone.setObjectName("icone")
        self.caixa_link_2 = QtWidgets.QLineEdit(self.page1)
        self.caixa_link_2.setGeometry(QtCore.QRect(240, 270, 601, 61))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        self.caixa_link_2.setFont(font)
        self.caixa_link_2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.caixa_link_2.setStyleSheet("color:black;\n"
"border-style:outset;\n"
"border-radius:15px;\n"
"border-width:3px;\n"
"background-color:rgb(234, 249, 249)")
        self.caixa_link_2.setInputMask("")
        self.caixa_link_2.setText("")
        self.caixa_link_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.caixa_link_2.setPlaceholderText("")
        self.caixa_link_2.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.caixa_link_2.setObjectName("caixa_link_2")
        self.radioButton_image = QtWidgets.QRadioButton(self.page1)
        self.radioButton_image.setGeometry(QtCore.QRect(290, 230, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.radioButton_image.setFont(font)
        self.radioButton_image.setStyleSheet("border:none;\n"
"font-family: Trebuchet MS;\n"
"font-size:14px;\n"
"color:white;\n"
"")
        self.radioButton_image.setObjectName("radioButton_image")
        self.radioButton_musica = QtWidgets.QRadioButton(self.page1)
        self.radioButton_musica.setGeometry(QtCore.QRect(460, 230, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.radioButton_musica.setFont(font)
        self.radioButton_musica.setStyleSheet("border:none;\n"
"font-family: Trebuchet MS;\n"
"font-size:14px;\n"
"color:white;\n"
"")
        self.radioButton_musica.setObjectName("radioButton_musica")
        self.radioButton_video_2 = QtWidgets.QRadioButton(self.page1)
        self.radioButton_video_2.setGeometry(QtCore.QRect(630, 230, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.radioButton_video_2.setFont(font)
        self.radioButton_video_2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.radioButton_video_2.setStyleSheet("border:none;\n"
"font-family: Trebuchet MS;\n"
"font-size:14px;\n"
"color:white;\n"
"")
        self.radioButton_video_2.setObjectName("radioButton_video_2")
        self.baixa_link = QtWidgets.QPushButton(self.page1)
        self.baixa_link.setGeometry(QtCore.QRect(230, 410, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.baixa_link.setFont(font)
        self.baixa_link.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0,0,0), stop:1 rgba(1, 181, 180));\n"
"")
        self.baixa_link.setObjectName("baixa_link")
        self.tela_2 = QtWidgets.QLabel(self.page1)
        self.tela_2.setGeometry(QtCore.QRect(420, 340, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tela_2.setFont(font)
        self.tela_2.setStyleSheet("color:white;\n"
"border-style:outset;\n"
"border-radius:5px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0,0,0), stop:1 rgba(1, 181, 180));\n"
"")
        self.tela_2.setText("")
        self.tela_2.setAlignment(QtCore.Qt.AlignCenter)
        self.tela_2.setObjectName("tela_2")
        self.label_welcome = QtWidgets.QLabel(self.page1)
        self.label_welcome.setGeometry(QtCore.QRect(20, 10, 260, 23))
        self.label_welcome.setStyleSheet("font-family: Trebuchet MS;\n"
"font-size: 15px;\n"
"font-weight: bold;\n"
"color: white;\n"
"border:none;\n"
"text-decoration:underline;\n"
"color:white;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0,0,0), stop:1 rgba(1, 181, 180));\n"
"")
        self.label_welcome.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_welcome.setObjectName("label_welcome")
        self.label_3 = QtWidgets.QLabel(self.page1)
        self.label_3.setGeometry(QtCore.QRect(280, 230, 161, 31))
        self.label_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-radius:12px;\n"
"border-width:0px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.page1)
        self.label_4.setGeometry(QtCore.QRect(450, 230, 161, 31))
        self.label_4.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-radius:12px;\n"
"border-width:0px;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.page1)
        self.label_5.setGeometry(QtCore.QRect(620, 230, 161, 31))
        self.label_5.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-radius:12px;\n"
"border-width:0px;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.limpar_pagina1 = QtWidgets.QPushButton(self.page1)
        self.limpar_pagina1.setGeometry(QtCore.QRect(680, 410, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.limpar_pagina1.setFont(font)
        self.limpar_pagina1.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0,0,0), stop:1 rgba(1, 181, 180));\n"
"")
        self.limpar_pagina1.setObjectName("limpar_pagina1")
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_3.raise_()
        self.TExt_Link.raise_()
        self.icone.raise_()
        self.caixa_link_2.raise_()
        self.radioButton_image.raise_()
        self.radioButton_musica.raise_()
        self.radioButton_video_2.raise_()
        self.baixa_link.raise_()
        self.tela_2.raise_()
        self.label_welcome.raise_()
        self.limpar_pagina1.raise_()
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.ver_link_2 = QtWidgets.QPushButton(self.page2)
        self.ver_link_2.setGeometry(QtCore.QRect(20, 630, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.ver_link_2.setFont(font)
        self.ver_link_2.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0,0,0), stop:1 rgba(1, 181, 180));\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ver_link_2.setIcon(icon)
        self.ver_link_2.setObjectName("ver_link_2")
        self.scrollArea_PAgina2 = QtWidgets.QScrollArea(self.page2)
        self.scrollArea_PAgina2.setGeometry(QtCore.QRect(10, 10, 1071, 571))
        self.scrollArea_PAgina2.setStyleSheet("\n"
"background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));\n"
"border-radius:12px;\n"
"border-width:0px;\n"
"")
        self.scrollArea_PAgina2.setWidgetResizable(True)
        self.scrollArea_PAgina2.setObjectName("scrollArea_PAgina2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1071, 571))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Open_pagina2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.Open_pagina2.setStyleSheet("border-style:outset;\n"
"border-radius:12px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.Open_pagina2.setText("")
        self.Open_pagina2.setObjectName("Open_pagina2")
        self.gridLayout_3.addWidget(self.Open_pagina2, 0, 0, 1, 1)
        self.scrollArea_PAgina2.setWidget(self.scrollAreaWidgetContents_2)
        self.inputAbrirArquivo_2 = QtWidgets.QLineEdit(self.page2)
        self.inputAbrirArquivo_2.setGeometry(QtCore.QRect(150, 630, 261, 31))
        self.inputAbrirArquivo_2.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:1px;\n"
"background-color: rgb(255, 255, 255);\n"
"color:black;")
        self.inputAbrirArquivo_2.setObjectName("inputAbrirArquivo_2")
        self.comboBox = QtWidgets.QComboBox(self.page2)
        self.comboBox.setGeometry(QtCore.QRect(30, 590, 91, 31))
        self.comboBox.setStyleSheet("border-style:outset;\n"
"border-radius:12px;\n"
"border-width:0px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0,0,0), stop:1 rgba(1, 181, 180));\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_pagina2 = QtWidgets.QLabel(self.page2)
        self.label_pagina2.setGeometry(QtCore.QRect(150, 670, 261, 31))
        self.label_pagina2.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:1px;\n"
"background-color: rgb(255, 255, 255);\n"
"color:black;")
        self.label_pagina2.setText("")
        self.label_pagina2.setObjectName("label_pagina2")
        self.pushButton = QtWidgets.QPushButton(self.page2)
        self.pushButton.setGeometry(QtCore.QRect(20, 670, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0,0,0), stop:1 rgba(1, 181, 180));\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.scrollArea_PAgina2.raise_()
        self.inputAbrirArquivo_2.raise_()
        self.comboBox.raise_()
        self.label_pagina2.raise_()
        self.pushButton.raise_()
        self.ver_link_2.raise_()
        self.stackedWidget.addWidget(self.page2)
        self.pagina3 = QtWidgets.QWidget()
        self.pagina3.setObjectName("pagina3")
        self.scrollArea = QtWidgets.QScrollArea(self.pagina3)
        self.scrollArea.setGeometry(QtCore.QRect(20, 10, 1041, 491))
        self.scrollArea.setStyleSheet("\n"
"background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));\n"
"border-radius:12px;\n"
"border-width:0px;\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1041, 491))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelImg = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelImg.setStyleSheet("border-style:outset;\n"
"border-radius:12px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.labelImg.setText("")
        self.labelImg.setObjectName("labelImg")
        self.gridLayout_2.addWidget(self.labelImg, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.inputAbrirArquivo = QtWidgets.QLineEdit(self.pagina3)
        self.inputAbrirArquivo.setGeometry(QtCore.QRect(180, 530, 331, 31))
        self.inputAbrirArquivo.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:1px;\n"
"background-color: rgb(255, 255, 255);\n"
"color:black;")
        self.inputAbrirArquivo.setText("")
        self.inputAbrirArquivo.setObjectName("inputAbrirArquivo")
        self.btnEscolherArquivo = QtWidgets.QPushButton(self.pagina3)
        self.btnEscolherArquivo.setGeometry(QtCore.QRect(20, 530, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(11)
        self.btnEscolherArquivo.setFont(font)
        self.btnEscolherArquivo.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0,0,0), stop:1 rgba(1, 181, 180));\n"
"")
        self.btnEscolherArquivo.setIcon(icon)
        self.btnEscolherArquivo.setObjectName("btnEscolherArquivo")
        self.label = QtWidgets.QLabel(self.pagina3)
        self.label.setGeometry(QtCore.QRect(30, 590, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0,0,0), stop:1 rgba(1, 181, 180));\n"
"")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.inputAltura = QtWidgets.QLineEdit(self.pagina3)
        self.inputAltura.setGeometry(QtCore.QRect(400, 600, 91, 21))
        self.inputAltura.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:black;\n"
"border-style:outset;\n"
"border-radius:8px;\n"
"border-width:0px;\n"
"")
        self.inputAltura.setObjectName("inputAltura")
        self.label_2 = QtWidgets.QLabel(self.pagina3)
        self.label_2.setGeometry(QtCore.QRect(300, 590, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0,0,0), stop:1 rgba(1, 181, 180));\n"
"")
        self.label_2.setObjectName("label_2")
        self.inputLargura = QtWidgets.QLineEdit(self.pagina3)
        self.inputLargura.setGeometry(QtCore.QRect(130, 600, 101, 22))
        self.inputLargura.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:black;\n"
"border-style:outset;\n"
"border-radius:8px;\n"
"border-width:0px;\n"
"color:black;")
        self.inputLargura.setObjectName("inputLargura")
        self.btnRedimensionar = QtWidgets.QPushButton(self.pagina3)
        self.btnRedimensionar.setGeometry(QtCore.QRect(50, 660, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        self.btnRedimensionar.setFont(font)
        self.btnRedimensionar.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0,0,0), stop:1 rgba(1, 181, 180));\n"
"")
        self.btnRedimensionar.setObjectName("btnRedimensionar")
        self.btnSalvar = QtWidgets.QPushButton(self.pagina3)
        self.btnSalvar.setGeometry(QtCore.QRect(210, 660, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        self.btnSalvar.setFont(font)
        self.btnSalvar.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0,0,0), stop:1 rgba(1, 181, 180));\n"
"")
        self.btnSalvar.setObjectName("btnSalvar")
        self.limpa_3 = QtWidgets.QPushButton(self.pagina3)
        self.limpa_3.setGeometry(QtCore.QRect(350, 660, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.limpa_3.setFont(font)
        self.limpa_3.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0,0,0), stop:1 rgba(1, 181, 180));\n"
"")
        self.limpa_3.setObjectName("limpa_3")
        self.stackedWidget.addWidget(self.pagina3)
        self.pagin4_cadastro = QtWidgets.QWidget()
        self.pagin4_cadastro.setObjectName("pagin4_cadastro")
        self.stackedWidget.addWidget(self.pagin4_cadastro)
        self.fundo_imagen = QtWidgets.QLabel(self.centralwidget)
        self.fundo_imagen.setGeometry(QtCore.QRect(10, -40, 1301, 831))
        self.fundo_imagen.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.fundo_imagen.setText("")
        self.fundo_imagen.setPixmap(QtGui.QPixmap("icon/fundo tela.jpg"))
        self.fundo_imagen.setObjectName("fundo_imagen")
        self.login_logado = QtWidgets.QLabel(self.centralwidget)
        self.login_logado.setGeometry(QtCore.QRect(20, 730, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.login_logado.setFont(font)
        self.login_logado.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0,0,0), stop:1 rgba(1, 181, 180));\n"
"")
        self.login_logado.setFrameShape(QtWidgets.QFrame.Box)
        self.login_logado.setText("")
        self.login_logado.setTextFormat(QtCore.Qt.PlainText)
        self.login_logado.setObjectName("login_logado")
        self.fundo_imagen.raise_()
        self.stackedWidget.raise_()
        self.login_logado.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionpagina = QtWidgets.QAction(MainWindow)
        self.actionpagina.setObjectName("actionpagina")
        self.actionpagina1 = QtWidgets.QAction(MainWindow)
        self.actionpagina1.setObjectName("actionpagina1")
        self.actionpagina2 = QtWidgets.QAction(MainWindow)
        self.actionpagina2.setObjectName("actionpagina2")
        self.actionPAGINA1 = QtWidgets.QAction(MainWindow)
        self.actionPAGINA1.setIcon(icon)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.actionPAGINA1.setFont(font)
        self.actionPAGINA1.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionPAGINA1.setObjectName("actionPAGINA1")
        self.actionPAGINA2 = QtWidgets.QAction(MainWindow)
        self.actionPAGINA2.setIcon(icon)
        self.actionPAGINA2.setObjectName("actionPAGINA2")
        self.actionPAGINA3 = QtWidgets.QAction(MainWindow)
        self.actionPAGINA3.setIcon(icon)
        self.actionPAGINA3.setObjectName("actionPAGINA3")
        self.actionFECHAR = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/cil-x-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFECHAR.setIcon(icon1)
        self.actionFECHAR.setObjectName("actionFECHAR")
        self.actionpagina4 = QtWidgets.QAction(MainWindow)
        self.actionpagina4.setObjectName("actionpagina4")
        self.actionPAGINA4 = QtWidgets.QAction(MainWindow)
        self.actionPAGINA4.setIcon(icon)
        self.actionPAGINA4.setObjectName("actionPAGINA4")
        self.toolBar.addAction(self.actionPAGINA1)
        self.toolBar.addAction(self.actionPAGINA2)
        self.toolBar.addAction(self.actionPAGINA3)
        self.toolBar.addAction(self.actionPAGINA4)
        self.toolBar.addAction(self.actionFECHAR)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.limpa_3.clicked.connect(self.inputAbrirArquivo.clear)
        self.limpar_pagina1.clicked.connect(self.caixa_link_2.clear)
        self.limpar_pagina1.clicked.connect(self.tela_2.clear)
        self.pushButton.clicked.connect(self.inputAbrirArquivo_2.clear)
        self.pushButton.clicked.connect(self.Open_pagina2.clear)
        self.limpa_3.clicked.connect(self.labelImg.clear)
        self.limpa_3.clicked.connect(self.inputAltura.clear)
        self.limpa_3.clicked.connect(self.inputLargura.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TExt_Link.setText(_translate("MainWindow", "  DIGITE O LINK ABAIXO"))
        self.radioButton_image.setText(_translate("MainWindow", "Image"))
        self.radioButton_musica.setText(_translate("MainWindow", "Musica"))
        self.radioButton_video_2.setText(_translate("MainWindow", "Video"))
        self.baixa_link.setText(_translate("MainWindow", "Baixar"))
        self.label_welcome.setText(_translate("MainWindow", "Bem vindo Usuario."))
        self.limpar_pagina1.setText(_translate("MainWindow", "Limpar"))
        self.ver_link_2.setText(_translate("MainWindow", "open"))
        self.comboBox.setItemText(1, _translate("MainWindow", "test"))
        self.comboBox.setItemText(2, _translate("MainWindow", "test"))
        self.pushButton.setText(_translate("MainWindow", "limpar"))
        self.inputAbrirArquivo.setPlaceholderText(_translate("MainWindow", "Caminho da foto"))
        self.btnEscolherArquivo.setText(_translate("MainWindow", "Escolher Arquivo"))
        self.label.setText(_translate("MainWindow", "  Largura"))
        self.inputAltura.setPlaceholderText(_translate("MainWindow", "Coloque Altura"))
        self.label_2.setText(_translate("MainWindow", "    Altura"))
        self.inputLargura.setPlaceholderText(_translate("MainWindow", "Coloque Largura"))
        self.btnRedimensionar.setText(_translate("MainWindow", "Redimensionar"))
        self.btnSalvar.setText(_translate("MainWindow", "Salvar"))
        self.limpa_3.setText(_translate("MainWindow", "Limpar"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionpagina.setText(_translate("MainWindow", "pagina"))
        self.actionpagina1.setText(_translate("MainWindow", "pagina1"))
        self.actionpagina2.setText(_translate("MainWindow", "pagina2"))
        self.actionPAGINA1.setText(_translate("MainWindow", "INICIAL"))
        self.actionPAGINA1.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">INICIAL</span></p></body></html>"))
        self.actionPAGINA1.setShortcut(_translate("MainWindow", "F1"))
        self.actionPAGINA2.setText(_translate("MainWindow", "SEGUNDATELA"))
        self.actionPAGINA2.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">SEGUNDA TELA</span></p></body></html>"))
        self.actionPAGINA2.setShortcut(_translate("MainWindow", "F2"))
        self.actionPAGINA3.setText(_translate("MainWindow", "TERCEIRATELA"))
        self.actionPAGINA3.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">TERCEIRATELA</span></p></body></html>"))
        self.actionPAGINA3.setShortcut(_translate("MainWindow", "F3"))
        self.actionFECHAR.setText(_translate("MainWindow", "FECHAR"))
        self.actionFECHAR.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">SAIR SISTEMA</span></p></body></html>"))
        self.actionFECHAR.setShortcut(_translate("MainWindow", "Esc"))
        self.actionpagina4.setText(_translate("MainWindow", "pagina4"))
        self.actionPAGINA4.setText(_translate("MainWindow", "PAGINA4"))
        self.actionPAGINA4.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">CADASTRO</span></p></body></html>"))
        self.actionPAGINA4.setShortcut(_translate("MainWindow", "F4"))
